:root{
  --bg:#f6f7fb; --card:#fff; --ink:#151827; --muted:#667085; --line:#e8ebf2;
  --purple:#7457e8; --soft-purple:#f0ecff; --green:#dff7e8; --blue:#e7f0ff; --pink:#ffe7ec; --orange:#fff0d8;
  --shadow:0 10px 30px rgba(25,30,50,.08); --radius:18px;
}
*{box-sizing:border-box} body{margin:0;background:var(--bg);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;color:var(--ink);padding:env(safe-area-inset-top) 14px 82px}
.app-header{display:flex;align-items:center;justify-content:space-between;padding:18px 4px 10px}.app-header h1{font-size:24px;margin:0}.app-header p{margin:4px 0 0;color:var(--muted)}
.icon-btn,.small-btn,.fab,button{border:0;border-radius:14px;background:var(--soft-purple);color:var(--purple);font-weight:700;padding:10px 14px;font-size:16px}.icon-btn{font-size:34px;line-height:20px;width:46px;height:46px}.small-btn{font-size:14px;background:#fff;border:1px solid #ded9ff}
.today-card,.planner-card,.list-card{background:var(--card);border-radius:var(--radius);box-shadow:var(--shadow);margin:12px 0;padding:18px}.today-card{display:flex;justify-content:space-between;gap:16px;align-items:center}.muted{color:var(--muted);margin:0}.today-card h2{margin:4px 0 0;font-size:21px}.progress-wrap{min-width:120px}.progress{height:10px;background:#edf0f5;border-radius:99px;overflow:hidden}.progress span{display:block;height:100%;width:0;background:var(--purple);border-radius:99px;transition:.25s}.progress-wrap small{display:block;margin-top:7px;color:var(--muted);font-size:12px;text-align:right}
.planner-top,.list-head{display:flex;align-items:center;justify-content:space-between}.planner-top h2,.list-head h2{margin:0 0 12px}.planner-scroll{overflow:auto;border:1px solid var(--line);border-radius:14px}.planner-grid{display:grid;grid-template-columns:110px repeat(7,72px);min-width:614px}.cell{border-right:1px solid var(--line);border-bottom:1px solid var(--line);min-height:68px;padding:7px;position:relative}.cell:nth-child(8n){border-right:0}.head{min-height:62px;text-align:center;font-weight:800;background:#fbfcff;position:sticky;top:0;z-index:3}.head.today{background:var(--soft-purple)}.head small{display:block;color:#ff7b00;margin-top:4px}.property{font-weight:800;font-size:13px;background:#fff;position:sticky;left:0;z-index:2;display:flex;align-items:center}.property .home-dot{width:26px;height:26px;border-radius:9px;margin-right:8px;background:var(--soft-purple);display:grid;place-items:center}.booking{position:absolute;top:9px;left:6px;right:6px;height:50px;border-radius:10px;border:1px solid; padding:7px 8px;overflow:hidden;font-size:11px;z-index:1}.booking strong{display:block;font-size:13px;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.b0{background:var(--green);border-color:#91daa8}.b1{background:var(--blue);border-color:#9ac0ff}.b2{background:var(--pink);border-color:#ff9aaa}.b3{background:var(--orange);border-color:#ffbf70}.b4{background:#efe8ff;border-color:#bca5ff}.done{opacity:.55;filter:saturate(.6)}
.pill{background:var(--green);color:#118343;border-radius:999px;padding:7px 10px;font-weight:800;font-size:13px}.today-list{display:grid;gap:10px}.clean-item{display:flex;align-items:center;gap:12px;background:#fbfcff;border:1px solid var(--line);border-radius:15px;padding:12px}.clean-item .avatar{width:42px;height:42px;border-radius:14px;background:var(--soft-purple);display:grid;place-items:center;font-size:22px}.clean-item strong{display:block}.clean-item small{color:var(--muted)}.clean-item button{margin-left:auto;font-size:13px;padding:9px 10px}.complete{background:var(--green);color:#118343}.waiting{background:#eef4ff;color:#155eef}
.bottom-nav{position:fixed;left:0;right:0;bottom:0;background:rgba(255,255,255,.95);border-top:1px solid var(--line);display:flex;justify-content:space-around;padding:10px 8px calc(10px + env(safe-area-inset-bottom));backdrop-filter:blur(12px)}.bottom-nav button{background:transparent;color:var(--muted);font-size:12px}.bottom-nav .active{color:var(--purple)}.fab{position:fixed;right:18px;bottom:78px;width:58px;height:58px;border-radius:18px;font-size:32px;background:var(--purple);color:#fff;box-shadow:var(--shadow)}
dialog{border:0;border-radius:22px;box-shadow:var(--shadow);width:min(94vw,520px);padding:0}dialog::backdrop{background:rgba(15,20,35,.35)}.dialog-form{padding:20px;display:grid;gap:12px}.dialog-form h2{margin:0 0 4px}label{display:grid;gap:6px;font-weight:700;color:#344054}input,select,textarea{border:1px solid #d6dbe6;border-radius:12px;padding:12px;font:inherit;background:#fff}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:10px}.dialog-actions{display:flex;justify-content:flex-end;gap:10px}.ghost{background:#f4f5f7;color:#475467}.danger{background:#ffe7ec;color:#d92d20}.detail-row{padding:10px 0;border-bottom:1px solid var(--line)}.detail-row small{display:block;color:var(--muted);margin-bottom:3px}.empty{color:var(--muted);padding:14px;text-align:center}
@media(max-width:420px){.planner-grid{grid-template-columns:96px repeat(7,66px);min-width:558px}.cell{padding:5px}.booking{font-size:10px}.booking strong{font-size:12px}.today-card{align-items:flex-start}.two-col{grid-template-columns:1fr}}
